[project]
name = "redy"
main_executable_name = "redy"
version = "0.1.0"
description = "official compiler of the brand-new programming language - redy"
homepage = "https://redylang.com"
c_version = "17"
cxx_version = "20"
author = "pugur"
author_email = "pugurmc@gmail.com"
